name: Weather Alerts Scheduler

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

jobs:
  run-weather-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger High UV Alerts API Endpoint
        env:
          API_URL: ${{ secrets.PROD_API_URL }} # E.g. https://api.travion.com/api/v1/weather/process-alerts
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$API_URL" ]; then
            echo "API_URL secret is missing."
            exit 1
          fi
          echo "Calling Weather Alerts API..."
          curl -X GET "$API_URL" \
            -H "Authorization: Bearer $CRON_SECRET" \
            --fail --silent --show-error
